const Router = require('@koa/router')
const router = new Router()
const shopinfoRouter = require("./shopinfo.routes")
const adsManagmentRouter = require("./adsManagment.routes")
const bikeCategoryRouter = require("./bikeCategory.routes")
const bikeInfoRouter = require("./bikeInfo.routes")
const clientRouter = require("./client.routes")
const paymentRouter = require("./payment.routes")
const penaltyRouter = require("./penalty.routes")
const rentalRouter = require("./rental.routes")
const userRouter = require("./user.routes")
const userGroupRouter = require("./user_group.routes")
const otp = require("./otp.routes")

router.use("/api/shopinfo", shopinfoRouter())
router.use("/api/ads", adsManagmentRouter())
router.use("/api/bikeCategory", bikeCategoryRouter())
router.use("/api/bikeInfo", bikeInfoRouter())
router.use("/api/client", clientRouter())
router.use("/api/payment", paymentRouter())
router.use("/api/penalty", penaltyRouter())
router.use("/api/rental", rentalRouter())
router.use("/api/user", userRouter())
router.use("/api/userGroup", userGroupRouter())
router.use("/api/otp", otp())

module.exports = router.routes()
